# pull official base image
FROM node

# set working directory
WORKDIR /app-f

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app-f/node_modules/.bin:$PATH

COPY . ./

ENTRYPOINT ["/bin/bash", "-c", "cd /app-f; npm install; npm run build; npm install -g serve; npx serve -s /app-f/build -l 3000; exec \"${@:0}\";"]
